default_platform(:ios)

TEAMID = ENV["TEAMID"]
GH_PAT = ENV["GH_PAT"]
GITHUB_WORKSPACE = ENV["GITHUB_WORKSPACE"]

FASTLANE_KEY_ID = ENV["FASTLANE_KEY_ID"]
FASTLANE_ISSUER_ID = ENV["FASTLANE_ISSUER_ID"]
FASTLANE_KEY = ENV["FASTLANE_KEY"]

platform :ios do
  desc "Build Linx Nightscout Bridge IPA"
  lane :build_bridge do
    setup_ci if ENV["CI"]

    sh("brew install xcodegen || true")
    sh("cd #{GITHUB_WORKSPACE} && xcodegen generate")

    update_project_team(
      path: "#{GITHUB_WORKSPACE}/LinxNightscoutBridge.xcodeproj",
      teamid: TEAMID
    )

    api_key = app_store_connect_api_key(
      key_id: FASTLANE_KEY_ID,
      issuer_id: FASTLANE_ISSUER_ID,
      key_content: FASTLANE_KEY
    )

    ENV["MATCH_READONLY"] = "false"

    match(
      type: "appstore",
      api_key: api_key,
      git_url: "https://github.com/Loop4Cati/Match-Secrets.git",
      git_basic_authorization: Base64.strict_encode64("x-access-token:#{GH_PAT}"),
      app_identifier: ["ro.heygluco.LinxNightscoutBridge"]
    )

    mapping = Actions.lane_context[
      SharedValues::MATCH_PROVISIONING_PROFILE_MAPPING
    ]

    update_code_signing_settings(
      path: "#{GITHUB_WORKSPACE}/LinxNightscoutBridge.xcodeproj",
      profile_name: mapping["ro.heygluco.LinxNightscoutBridge"],
      code_sign_identity: "Apple Distribution",
      targets: ["LinxNightscoutBridge"]
    )

    gym(
      project: "#{GITHUB_WORKSPACE}/LinxNightscoutBridge.xcodeproj",
      scheme: "LinxNightscoutBridge",
      configuration: "Release",
      export_method: "app-store",
      output_name: "LinxNightscoutBridge.ipa",
      destination: "generic/platform=iOS",
      buildlog_path: "#{GITHUB_WORKSPACE}/buildlog"
    )

    copy_artifacts(
      target_path: "#{GITHUB_WORKSPACE}/artifacts",
      artifacts: ["*.ipa", "*.dSYM.zip", "*.mobileprovision"]
    )

    upload_to_testflight(
      api_key: api_key,
      ipa: "LinxNightscoutBridge.ipa",
      skip_waiting_for_build_processing: true
    )
  end
end
